name: Build APK

on:
  push:
  workflow_dispatch:
    inputs:
      XRAY_CORE_VERSION:
        description: 'Xray core version or commit hash'
        required: false


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Golang
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.2'

    - name: Install gomobile
      run: |
        go install golang.org/x/mobile/cmd/gomobile@latest
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH


    - name: Setup Android environment
      uses: android-actions/setup-android@v3


    - name: Build dependencies
      run: |
        mkdir ${{ github.workspace }}/build
        cd ${{ github.workspace }}/build
        git clone --depth=1 -b main https://github.com/2dust/AndroidLibXrayLite.git
        cd AndroidLibXrayLite
        go get github.com/xtls/xray-core@${{ github.event.inputs.XRAY_CORE_VERSION }} || true
        gomobile init
        go mod tidy -v
        gomobile bind -v -androidapi 19 -ldflags='-s -w' ./
        cp *.aar ${{ github.workspace }}/V2rayNG/app/libs/

    - name: Build APK
      run: |
        cd ${{ github.workspace }}/V2rayNG
        chmod 755 gradlew
        ./gradlew assembleDebug
        
    - name: Remove useless
      run: |
        rm ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/debug/YiLink_1.9.1_riscv64.apk
        rm ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/debug/YiLink_1.9.1_mips64.apk
        rm ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/debug/YiLink_1.9.1_mips.apk
        rm ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/debug/YiLink_1.9.1_armeabi.apk

    - name: Upload Aritfact (universal)
      uses: actions/upload-artifact@v4
      with:
        name: Debug Unsigned APK (universal) 
        path: ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/debug/*all.apk
      
    - name: Upload Aritfact (arm64-v8a)
      uses: actions/upload-artifact@v4
      with:
        name: Debug Unsigned APK (arm64-v8a)
        path: ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/debug/*arm64-v8a.apk
      
    - name: Upload Aritfact (armeabi-v7a)
      uses: actions/upload-artifact@v4
      with:
        name: Debug Unsigned APK (armeabi-v7a)
        path: ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/debug/*armeabi-v7a.apk
      
    - name: Upload Aritfact (x86_64)
      uses: actions/upload-artifact@v4
      with:
        name: Debug Unsigned APK (x86_64)
        path: ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/debug/*x86_64.apk
          